'use client';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import type { Collaborator } from '@/lib/types';
import { useEffect, useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { getRandomColor, avatarColors } from '@/lib/colors';
import { Check, Eye, EyeOff } from 'lucide-react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface CollaboratorFormDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (data: any) => void;
  collaborator: Collaborator | null;
}

export function CollaboratorFormDialog({
  isOpen,
  onClose,
  onSave,
  collaborator,
}: CollaboratorFormDialogProps) {
  const [name, setName] = useState('');
  const [role, setRole] = useState<'admin' | 'collaborator'>('collaborator');
  const [avatarColor, setAvatarColor] = useState(getRandomColor());
  
  const { toast } = useToast();

  const isEditMode = !!collaborator;

  useEffect(() => {
    if (isOpen) {
      if (collaborator) {
        setName(collaborator.name);
        setRole(collaborator.role);
        setAvatarColor(collaborator.avatarColor || getRandomColor());
      } else {
        // Reset form for creation
        setName('');
        setRole('collaborator');
        setAvatarColor(getRandomColor());
      }
    }
  }, [collaborator, isOpen]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (isEditMode) {
        if (!name) {
            toast({
                variant: "destructive",
                title: "Champ manquant",
                description: "Le nom est requis.",
            });
            return;
        }
        // In edit mode, we only update editable fields
        onSave({ name, role, avatarColor });
    } else {
        if (!name) {
            toast({
                variant: "destructive",
                title: "Champ manquant",
                description: "Veuillez saisir le nom complet.",
            });
            return;
        }
        // In create mode, only name, role, and color are sent.
        // Username and password will be generated by the API.
        onSave({ name, role, avatarColor });
    }
  };

  const getInitials = (name: string) => {
    if (!name) return '??';
    return name
      .split(' ')
      .map((n) => n[0])
      .slice(0, 2)
      .join('');
  }

  return (
    <>
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md">
        <form onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>
              {isEditMode ? 'Modifier le Collaborateur' : 'Créer un Collaborateur'}
            </DialogTitle>
            <DialogDescription>
              {isEditMode
                ? "Modifier les détails de ce collaborateur."
                : "Le nom d'utilisateur et un mot de passe sécurisé seront générés automatiquement."}
            </DialogDescription>
          </DialogHeader>
          
          <div className="grid gap-4 py-6">

             <div className="grid grid-cols-4 items-center gap-4">
                <Label className="text-right">Avatar</Label>
                <div className="col-span-3 flex items-center gap-4">
                    <Avatar className="h-12 w-12">
                        <AvatarFallback style={{ backgroundColor: avatarColor }} className="text-white font-bold">
                            {getInitials(name)}
                        </AvatarFallback>
                    </Avatar>
                     <div className="flex flex-wrap gap-2">
                        {avatarColors.map(color => (
                            <div
                                key={color}
                                className="h-6 w-6 rounded-full cursor-pointer flex items-center justify-center"
                                style={{ backgroundColor: color }}
                                onClick={() => setAvatarColor(color)}
                            >
                               {avatarColor === color && <Check className="h-4 w-4 text-white" />}
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="name" className="text-right">
                Nom complet
              </Label>
              <Input
                id="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="col-span-3"
                required
                placeholder="Ex: Jean Dupont"
              />
            </div>
            
             <div className="grid grid-cols-4 items-center gap-4">
                <Label htmlFor="role" className="text-right">
                    Rôle
                </Label>
                 <Select onValueChange={(value) => setRole(value as any)} value={role} required>
                    <SelectTrigger id="role" className="col-span-3">
                        <SelectValue placeholder="Sélectionner un rôle" />
                    </SelectTrigger>
                    <SelectContent>
                        <SelectItem value="collaborator">Collaborateur</SelectItem>
                        <SelectItem value="admin">Administrateur</SelectItem>
                    </SelectContent>
                </Select>
            </div>
            
            {!isEditMode && (
              <p className="text-sm text-muted-foreground col-span-4 text-center pt-2">
                Un nom d'utilisateur et un mot de passe seront générés et affichés après l'enregistrement.
              </p>
            )}
          </div>
          
          <DialogFooter>
            <Button type="button" variant="ghost" onClick={onClose}>
              Annuler
            </Button>
            <Button type="submit">Enregistrer</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
    </>
  );
}
